name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Publish artifacts
        run: script/ci/can-release && script/ci/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
