name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Publish artifacts
        run: script/ci/can-release && script/ci/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables for Docker image
        id: variables
        run: |
          git_tag_name="${GITHUB_REF#refs/tags/}"
          git_tag_name="${git_tag_name#v}"
          echo "::set-output name=release_tag_patch::${git_tag_name}"
          echo "::set-output name=release_tag_minor::${git_tag_name%.*}"
          echo "::set-output name=node_version::$(cat .node-version)"

      - name: Build and release Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: fireworq/fireworqonsole
          tags: latest, ${{ steps.variables.outputs.release_tag_patch }}, ${{ steps.variables.outputs.release_tag_minor }}
          build_args: NODE_VERSION=${{ steps.variables.outputs.node_version }}
